# Generated by Django 4.0.3 on 2022-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Pin_code', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('Photo', models.ImageField(upload_to='media')),
            ],
        ),
    ]
