# Generated by Django 4.0.3 on 2022-07-06 16:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_aboutmodel_summary'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aboutmodel',
            managers=[
                ('aboutme', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Bio1',
            field=models.CharField(default='Data Scientist', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Bio2',
            field=models.CharField(default='Tableau Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Home_bg1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Home_bg2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Phone_number',
            field=models.CharField(blank=True, default='9988776655', max_length=10),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Profile_photo',
            field=models.ImageField(blank=True, default='default_profile.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Address',
            field=models.CharField(blank=True, default='Chennai', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='DOB',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Email',
            field=models.EmailField(default='sample@yourdomain.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Name',
            field=models.CharField(default='Revan', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Pin_code',
            field=models.CharField(default='639 120', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Summary',
            field=models.TextField(default='\n            A small river named Duden flows by their place and \n            supplies it with the necessary regelialia. \n            It is a paradisematic country, in which roasted parts \n            of sentences fly into your mouth.\n', max_length=250),
        ),
    ]
